apiVersion: v1
kind: Service
metadata:
    name: goglitch
spec:
    ports:
      - port: 3000
        targetPort: 3000
        protocol: TCP
    selector:
        app: goglitch
    externalIPs:
      - 52.207.221.68
    type: NodePort

---
apiVersion: v1
kind: ReplicationController
metadata:
    name: goglitch
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: goglitch
        spec:
            containers:
              - name: goglitch
                imagePullPolicy: Always
                command: [
                    "./goglitch"
                ]
                image: quay.io/faiq/goglitch
                ports:
                  - containerPort: 3000
