apiVersion: v1
kind: Service
metadata:
    name: goglitch
spec:
    type: NodePort
    ports:
      - port: 1300
        targetPort: 1300
        protocol: TCP
    selector:
        app: goglitch
    externalIPs:
      - "80.11.12.10"

apiVersion: v1
kind: ReplicationController
metadata:
    name: goglitch
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: goglitch
        spec:
            containers:
              - name: goglitch
                imagePullPolicy: Always
                command: [
                    "./goglitch"
                ]
                image: quay.io/faiq/goglitch
                ports:
                  - containerPort: 3000
